//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grimdate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Updater {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Updater() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("grimdate.Updater", typeof(Updater).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/0zl/grimlite/raw/main/checksum.txt.
        /// </summary>
        internal static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/0zl/meow/commits.
        /// </summary>
        internal static string CommitAPI {
            get {
                return ResourceManager.GetString("CommitAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/0zl/meow/compare/19a685bc59b334505041f0ce12d4bd46f4204029....
        /// </summary>
        internal static string CompareAPI {
            get {
                return ResourceManager.GetString("CompareAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/0zl/grimlite/raw/main/Grimoire.exe.
        /// </summary>
        internal static string EXE {
            get {
                return ResourceManager.GetString("EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;&gt;
        ///            &lt;section name=&quot;Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot;/&gt;
        ///        &lt;/sectionGroup&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GrimConf {
            get {
                return ResourceManager.GetString("GrimConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/0zl/grimlite/raw/main/libs.txt.
        /// </summary>
        internal static string Libs {
            get {
                return ResourceManager.GetString("Libs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/0zl/grimlite/raw/main/catgirl.swf.
        /// </summary>
        internal static string SWF {
            get {
                return ResourceManager.GetString("SWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcceptQuestColor=FFA1F3F6
        ///CompleteQuestColor=FF9FA8FD
        ///BankListColor=FFAA87D6
        ///ClearTempColor=FF8C97A7
        ///BeepColor=FF8ADD92
        ///BlankColor=FFA380CD
        ///Blank2Color=FF86CFC9
        ///BotDelayColor=FF9B9E90
        ///ChangeColor=FF98E182
        ///ClientMessageColor=FFBBCAA8
        ///DelayColor=FFBF81E7
        ///GotoLabelColor=FFA6E5E8
        ///GotoPlayerColor=FFEA95FE
        ///IndexColor=FF80FFFF
        ///IntColor=FFE89A9C
        ///LabelColor=FFA093CF
        ///LoadBotColor=FF9FCF93
        ///ReturnColor=FFB6A8E3
        ///LogColor=FFF985D5
        ///LogoutColor=FFE586C5
        ///PacketDelayColor=FFFAEEBC
        ///PacketSpammerColor=FFAD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserConf {
            get {
                return ResourceManager.GetString("UserConf", resourceCulture);
            }
        }
    }
}
